"""Generated by tools/generate_export_stubs.py; do not edit directly."""

__all__: tuple[str, ...]

from cereja.hashtools._compress import (
    CompressionError as CompressionError,
    CompressionStats as CompressionStats,
    CompressionStrategy as CompressionStrategy,
    analyze_data as analyze_data,
    compress as compress,
    compress_dir as compress_dir,
    compress_file as compress_file,
    decompress as decompress,
    decompress_dir as decompress_dir,
    decompress_file as decompress_file,
    get_compression_ratio as get_compression_ratio,
    is_encrypted_archive as is_encrypted_archive,
    suggest_strategy as suggest_strategy,
)
from cereja.hashtools._crypto import (
    CryptoError as CryptoError,
    decrypt as decrypt,
    decrypt_file as decrypt_file,
    encrypt as encrypt,
    encrypt_file as encrypt_file,
    generate_key as generate_key,
)
from cereja.hashtools._hash import (
    base64_decode as base64_decode,
    base64_encode as base64_encode,
    is_base64 as is_base64,
    md5 as md5,
    random_hash as random_hash,
)
