"""Generated by tools/generate_export_stubs.py; do not edit directly."""

import sys

__all__: tuple[str, ...]

from cereja._version import __version__ as __version__
def print_cereja_version() -> bool: ...

import cereja.array as array
import cereja.utils.colab as colab
import cereja.utils.colors as colors
import cereja.system.commons as commons
import cereja.concurrently as concurrently
import cereja.config.conf as conf
import cereja.config as config
import cereja.mltools.data as data
import cereja.date as date
import cereja.utils.decorators as decorators
import cereja.display as display
import cereja.experimental as experimental
import cereja.file as file
import cereja.geolinear as geolinear
import cereja.utils.git as git
import cereja.hashtools as hashtools
import cereja.mathtools as mathtools
import cereja.mltools as mltools
import cereja.mltools.pln as pln
import cereja.mltools.preprocess as preprocess
import cereja.concurrently.process as process
import cereja._requests.request as request
import cereja.scraping as scraping
import cereja.mltools.split_data as split_data
import cereja.system as system
import cereja.utils.time as time
import cereja.utils.typography as typography
import cereja.system.unicode as unicode
import cereja.utils as utils
import cereja.utils.version as version
import cereja.wcag as wcag
from cereja._terminal import (
    NON_BMP_SUPPORTED as NON_BMP_SUPPORTED,
)
from cereja._version import (
    VERSION as VERSION,
)
from cereja.array._array import (
    Matrix as Matrix,
    apply_proportional_mask as apply_proportional_mask,
    array_gen as array_gen,
    array_randn as array_randn,
    determinant as determinant,
    div as div,
    dot as dot,
    dotproduct as dotproduct,
    flatten as flatten,
    get_cols as get_cols,
    get_min_max as get_min_max,
    get_shape as get_shape,
    is_empty as is_empty,
    prod as prod,
    rand_n as rand_n,
    rand_uniform as rand_uniform,
    remove_duplicate_items as remove_duplicate_items,
    reshape as reshape,
    shape_is_ok as shape_is_ok,
    sub as sub,
)
from cereja.concurrently._concurrence import (
    TaskList as TaskList,
    AsyncToSync as async_to_sync,
    SyncToAsync as sync_to_async,
)
from cereja.concurrently.process import (
    MultiProcess as MultiProcess,
    Processor as Processor,
)
from cereja.date._datetime import (
    AmbiguousDateFormatError as AmbiguousDateFormatError,
    DateTime as DateTime,
)
from cereja.display._display import (
    Progress as Progress,
    State as State,
    console as console,
)
from cereja.file._io import (
    FileIO as FileIO,
)
from cereja.hashtools._compress import (
    CompressionError as CompressionError,
    CompressionStats as CompressionStats,
    CompressionStrategy as CompressionStrategy,
    analyze_data as analyze_data,
    compress as compress,
    compress_dir as compress_dir,
    compress_file as compress_file,
    decompress as decompress,
    decompress_dir as decompress_dir,
    decompress_file as decompress_file,
    get_compression_ratio as get_compression_ratio,
    is_encrypted_archive as is_encrypted_archive,
    suggest_strategy as suggest_strategy,
)
from cereja.hashtools._crypto import (
    CryptoError as CryptoError,
    decrypt as decrypt,
    decrypt_file as decrypt_file,
    encrypt as encrypt,
    encrypt_file as encrypt_file,
    generate_key as generate_key,
)
from cereja.hashtools._hash import (
    base64_decode as base64_decode,
    base64_encode as base64_encode,
    is_base64 as is_base64,
    md5 as md5,
    random_hash as random_hash,
)
from cereja.mathtools._op import (
    degrees_to_radian as degrees_to_radian,
    distance_between_points as distance_between_points,
    estimate as estimate,
    greatest_common_multiple as greatest_common_multiple,
    imc as imc,
    least_common_multiple as least_common_multiple,
    nth_fibonacci_number as nth_fibonacci_number,
    percent as percent,
    proportional as proportional,
    radian_to_degrees as radian_to_degrees,
    theta_angle as theta_angle,
    theta_from_array as theta_from_array,
)
from cereja.mltools.data import (
    ConnectValues as ConnectValues,
    DataGenerator as DataGenerator,
    Freq as Freq,
    TfIdf as TfIdf,
    Tokenizer as Tokenizer,
)
from cereja.mltools.pln import (
    LanguageData as LanguageData,
    LanguageDetector as LanguageDetector,
    Preprocessor as Preprocessor,
)
from cereja.mltools.split_data import (
    Corpus as Corpus,
)
from cereja.system._context.cache import (
    clear_context_cache as clear_context_cache,
    get_context_cache_info as get_context_cache_info,
)
from cereja.system._context.cache_db import (
    CacheDatabaseUnavailable as CacheDatabaseUnavailable,
)
from cereja.system._context.models import (
    ContextCacheClearReport as ContextCacheClearReport,
    ContextCacheInfo as ContextCacheInfo,
    ContextCacheWarning as ContextCacheWarning,
    ContextResponse as ContextResponse,
    ContextResult as ContextResult,
    ContextSnippet as ContextSnippet,
    SkippedFile as SkippedFile,
)
from cereja.system._context.query import (
    context_response_to_dict as context_response_to_dict,
)
from cereja.system._context.search import (
    list_text_context as list_text_context,
    search_text_context as search_text_context,
)
from cereja.system._path import (
    Path as Path,
    TempDir as TempDir,
    change_date_from_path as change_date_from_path,
    clean_dir as clean_dir,
    file_name as file_name,
    get_base_dir as get_base_dir,
    group_path_from_dir as group_path_from_dir,
    mkdir as mkdir,
    normalize_path as normalize_path,
)
from cereja.system._repository_files import (
    RepositoryFile as RepositoryFile,
    iter_repository_files as iter_repository_files,
)
from cereja.system._repository_tree import (
    render_repository_tree as render_repository_tree,
)
from cereja.system.commons import (
    memory_of_this as memory_of_this,
    memory_usage as memory_usage,
    run_on_terminal as run_on_terminal,
    thread_monitor as thread_monitor,
)
from cereja.system.unicode import (
    Unicode as Unicode,
)
from cereja.utils._traceback import (
    format_safe_traceback as format_safe_traceback,
)
from cereja.utils._utils import (
    CjTest as CjTest,
    DataAnalyzer as DataAnalyzer,
    DataIterator as DataIterator,
    PoolMeta as PoolMeta,
    SingletonMeta as SingletonMeta,
    Source as Source,
    SourceCodeAnalyzer as SourceCodeAnalyzer,
    camel_case_to_snake as camel_case_to_snake,
    camel_to_snake as camel_to_snake,
    can_do as can_do,
    check_type_on_sequence as check_type_on_sequence,
    chunk as chunk,
    clipboard as clipboard,
    combinations as combinations,
    combinations_sizes as combinations_sizes,
    combine_with_all as combine_with_all,
    decode_coordinates as decode_coordinates,
    dict_append as dict_append,
    dict_filter_value as dict_filter_value,
    dict_max_value as dict_max_value,
    dict_min_value as dict_min_value,
    dict_to_tuple as dict_to_tuple,
    dict_values_len as dict_values_len,
    encode_coordinates as encode_coordinates,
    fill as fill,
    get_attr_if_exists as get_attr_if_exists,
    get_batch_strides as get_batch_strides,
    get_implements as get_implements,
    get_instances_of as get_instances_of,
    get_zero_mask as get_zero_mask,
    group_by as group_by,
    has_length as has_length,
    import_string as import_string,
    install_if_not as install_if_not,
    invert_dict as invert_dict,
    is_indexable as is_indexable,
    is_iterable as is_iterable,
    is_numeric_sequence as is_numeric_sequence,
    is_sequence as is_sequence,
    list_methods as list_methods,
    list_to_tuple as list_to_tuple,
    logger_level as logger_level,
    map_values as map_values,
    module_references as module_references,
    obj_repr as obj_repr,
    prune_values as prune_values,
    rescale_values as rescale_values,
    sample as sample,
    set_log_level as set_log_level,
    snake_case_to_camel as snake_case_to_camel,
    sort_dict as sort_dict,
    split_sequence as split_sequence,
    str_gen as str_gen,
    get_batch_strides as stride_values,
    string_to_literal as string_to_literal,
    to_tuple as to_tuple,
    truncate as truncate,
    type_table_of as type_table_of,
    value_from_memory as value_from_memory,
    visualize_sample as visualize_sample,
)
from cereja.utils.git.repository import (
    GitRepository as GitRepository,
)
from cereja.utils.time import (
    Timer as Timer,
    set_interval as set_interval,
    time_format as time_format,
)
from cereja.utils.version import (
    get_version as get_version,
    get_version_pep440_compliant as get_version_pep440_compliant,
    latest_git as latest_git,
)

if sys.platform == "win32":
    from cereja.system._screen_capture import (
        ScreenCapture as ScreenCapture,
        ScreenFrame as ScreenFrame,
        ScreenMonitor as ScreenMonitor,
    )
    from cereja.system._win32 import (
        Keyboard as Keyboard,
        Mouse as Mouse,
        Window as Window,
        play_alert_sound as play_alert_sound,
    )
