"""Render explicit IDE/type-checker exports without importing implementations.

Run this after editing cereja/_exports.py. CI uses --check to prevent drift.
"""

import argparse
from pathlib import Path
import runpy

ROOT = Path(__file__).resolve().parents[1]


def render(package, exports, windows):
    lines = ['"""Generated by tools/generate_export_stubs.py; do not edit directly."""', '']
    if windows:
        lines.extend(['import sys', ''])
    lines.extend(['__all__: tuple[str, ...]', ''])
    if package == 'cereja':
        lines.extend([
            'from cereja._version import __version__ as __version__',
            'def print_cereja_version() -> bool: ...',
            '',
        ])
    def declarations(items, indent=''):
        groups = {}
        modules = []
        for name, (module, attribute) in sorted(items.items()):
            if attribute is None:
                modules.append(f'{indent}import {module} as {name}')
            else:
                groups.setdefault(module, []).append((attribute, name))
        result = modules
        for module, names in sorted(groups.items()):
            result.append(f'{indent}from {module} import (')
            result.extend(f'{indent}    {attribute} as {name},' for attribute, name in names)
            result.append(f'{indent})')
        return result

    ordinary = {
        name: target for name, target in exports.items()
        if name not in windows and not (package == 'cereja' and name == 'print_cereja_version')
    }
    lines.extend(declarations(ordinary))
    if windows:
        lines.extend(['', 'if sys.platform == "win32":'])
        lines.extend(declarations(windows, '    '))
    return '\n'.join(lines) + '\n'


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args(argv)
    registry = runpy.run_path(str(ROOT / 'cereja' / '_exports.py'))
    stale = []
    for package, exports in sorted(registry['EXPORTS'].items()):
        path = ROOT.joinpath(*package.split('.'), '__init__.pyi')
        content = render(package, exports, registry['WINDOWS_EXPORTS'].get(package, {}))
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8') != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(content, encoding='utf-8', newline='\n')
    if stale:
        parser.exit(1, 'Stale or missing export stubs:\n' + '\n'.join(stale) + '\n')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
